version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: ludichile_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ludichile
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: